### ISSUE TITLE
small opinion regarding signup code 

### ISSUE THREAD

**Issue by GunarajKhatri** [TheBinitGhimire/IntuitiveContacts#7]
**what about redirection of user to sign in form after signup ?**
**Why?Reason:** Stop creation of  refresh token which reduces cookie space obviously & reduce lines of code

**Comment by TheBinitGhimire** [comment]
The creation of refresh token is there for the fulfillment of project requirements.

Also, currently the user is automatically authenticated into the platform right after sign-up, instead of having to sign-in again. The reason why I am doing this is because I haven't implemented any sort of user email/phone verification for account confirmation, which makes the redirection back to sign-in page/form most likely useless.

**Comment by GunarajKhatri** [comment]
OK got it !! I think as there is implementation of user's email verification though it wasn't there.

**Comment by TheBinitGhimire** [comment]
Oh, ok, that is fine then!

Still, thank you for opening up this issue!
